#!/bin/bash
# 模型下载脚本
# 使用方法: bash download_model.sh

MODEL_DIR="./models/Qwen3-TTS-1.7B"
mkdir -p "$MODEL_DIR"

echo "=========================================="
echo "Qwen3-TTS 模型下载脚本"
echo "=========================================="
echo ""
echo "由于网络问题自动下载失败，请选择以下方式手动下载："
echo ""
echo "方法 1: 从 ModelScope 下载"
echo "  1. 访问: https://modelscope.cn/models/qwen/Qwen3-TTS-1.7B"
echo "  2. 登录账号"
echo "  3. 点击下载"
echo "  4. 将文件放到: $MODEL_DIR/"
echo ""
echo "方法 2: 从 HuggingFace 下载"
echo "  1. 访问: https://huggingface.co/Qwen/Qwen3-TTS-1.7B"
echo "  2. 使用代理下载"
echo "  3. 将文件放到: $MODEL_DIR/"
echo ""
echo "方法 3: 配置代理后重试"
echo "  export HTTP_PROXY=http://127.0.0.1:7890"
echo "  export HTTPS_PROXY=http://127.0.0.1:7890"
echo "  python -m src.cli download"
echo ""
echo "所需文件:"
echo "  - config.json"
echo "  - model.safetensors"
echo "  - tokenizer.json"
echo "  - vocab.txt"
echo ""
echo "下载完成后运行:"
echo "  python -m src.cli speak \"你好\" -m qwen"
